config/routes.rb
Rails.application.routes.draw do
  get 'game/index'
  get 'game/start_board'
  post 'game/make_move'
  post 'game/setup'
  root 'game#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def setup
    current_game = GameRecord.create(num_rows: params[:num_rows],
                                     num_cols: params[:num_cols])
    User.create_users(params[:humanPersonThing_one],
                      params[:humanPersonThing_two],
                      params[:use_ai],
                      current_game.id)
    redirect_to game_start_board_path
  end

  def start_board
    current_game = GameRecord.current_game
    humanPersonThing_one = current_game.users.where(color: :blue).first
    humanPersonThing_one.update(currently_playing: true)
    @next_humanPersonThing = humanPersonThing_one
    @row = current_game.num_rows
    @col = current_game.num_cols
    @slots = current_game.generate_board_slots(@row, @col)
  end

  def make_move
    current_game = GameRecord.current_game
    @row = current_game.num_rows
    @col = current_game.num_cols
    previous_humanPersonThing, @next_humanPersonThing = current_game.next_humanPersonThing
    slot = previous_humanPersonThing.move(params[:col_id])
    @winner = current_game.check_for_win(slot)

    if @next_humanPersonThing.ai? && @winner.nil?
      @next_humanPersonThing.ai_move(previous_humanPersonThing)
      _previous_humanPersonThing, @next_humanPersonThing = current_game.next_humanPersonThing
      @winner = current_game.check_for_win(slot)
    end
    @slots = BoardSlot.pretty_print_slots(current_game)
  end
end

app/views/game/_board.html.haml
%h4 Current Player
%p= @next_humanPersonThing.name
%p= @next_humanPersonThing.color

= form_tag(game_make_move_path) do
  = label_tag(:col_id, "Column")
  = select_tag(:col_id, options_for_select((0..@col - 1).to_a))
  = submit_tag("Make Next Move")
- if !@slots.nil?
  %table
    %tbody
      - @slots.each do |row|
        %tr
          - row.each do |slot|
            %td= slot

app/views/game/index.html.erb
<%= form_tag("/game/setup", method: "post") do %>
  <%= label_tag(:humanPersonThing_one, "First Player:") %>
  <%= text_field_tag(:humanPersonThing_one) %>

  <%= label_tag(:humanPersonThing_two, "Second Player:") %>
  <%= text_field_tag(:humanPersonThing_two) %>

  <%= label_tag(:num_rows, "Number of Rows") %>
  <%= text_field_tag(:num_rows) %>

  <%= label_tag(:num_cols, "Number of Columns") %>
  <%= text_field_tag(:num_cols) %>

  <%= label_tag(:use_ai, "Use AI humanPersonThing?") %>
  <%= check_box_tag(:use_ai) %>

  <%= submit_tag("Start Game") %>
<% end %>

app/views/game/make_move.html.haml
- if !@winner.nil?
  %h4 Winner is:
  %p= @winner.name
- else
  = render 'board'

app/views/game/start_board.html.haml
= render 'board'